# Generated by Django 5.2.3 on 2025-06-22 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matchday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Group Stage – Matchday 1', 'Group Stage – Matchday 1'), ('Group Stage – Matchday 2', 'Group Stage – Matchday 2'), ('Group Stage – Matchday 3', 'Group Stage – Matchday 3'), ('Quarter-finals', 'Quarter-finals'), ('Semi-finals', 'Semi-finals'), ('Final', 'Final')], max_length=30, unique=True)),
                ('order', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fifa_code', models.CharField(max_length=3, unique=True)),
                ('flag_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=30)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fixtures.team')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kickoff_time', models.DateTimeField()),
                ('stage', models.CharField(max_length=50)),
                ('round_name', models.CharField(max_length=50)),
                ('score_team1', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('score_team2', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('matchday', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches', to='fixtures.matchday')),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='fixtures.team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='fixtures.team')),
            ],
        ),
    ]
