# Generated by Django 5.2.3 on 2025-06-27 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0002_alter_match_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='team2',
            new_name='away',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='round_name',
            new_name='day_of_week',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='team1',
            new_name='home',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='score_team1',
            new_name='score_away',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='score_team2',
            new_name='score_home',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='stage',
            new_name='venue',
        ),
    ]
